import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Topbar from '@/components/shared/Topbar'
import Bottombar from '@/components/shared/Bottombar'
import LeftSide from '@/components/shared/LeftSide'
import RightSide from '@/components/shared/RightSide'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SayIt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      
      <body className={inter.className}>
        <Topbar />
       <main className='flex flex-row'>
        <LeftSide />
          <section className='main-container'>
            <div className='w-full max-w-4xl'>

              {children}
            </div>

          </section>
        <RightSide />
       </main>
        <Bottombar />
      </body>
    </html>

    </ClerkProvider>
    
  )
}
